#!/usr/bin/python3

# -*- coding: utf-8 -*-
#########################################################
# SCRIPT : WebPassword                                  #
#          Hash password to store in xml file,          #
#          do not store in the clear                    #
#          I. Helwegen 2021                             #
#########################################################

####################### IMPORTS #########################
import getpass
import os
from webif.common import common, password
from webif.websettings import websettings
from sys import argv, exit

#########################################################

####################### GLOBALS #########################
APP_NAME = "smarthome"
#########################################################

###################### FUNCTIONS ########################

#########################################################

######################### MAIN ##########################
if __name__ == "__main__":
    print("Password hashing tool for SmartHome web app")
    if os.getuid() != 0:
        print("Please run as superuser: sudo WebPassword")
        exit(1)
    if len(argv) > 2:
        user = argv[1]
        pswd = argv[2]
    else:
        user = input('Please enter username:')
        pswd = getpass.getpass('Please enter password:')
        pswd2 = getpass.getpass('Please enter password again:')
        if pswd != pswd2:
            print("Error: Passwords don't match")
            exit(1)
    settings = websettings(__file__, APP_NAME)
    settings.setSetting("username", user)
    settings.setSetting("password", password().HashPass(pswd))
    settings.update()
    print("Ready")
